version: '3'
services:
  nginx:
    restart: always
    image: 'rcsouz/multi-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'

  server:
    image: 'rcsouz/multi-server'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT

  client:
    image: 'rcsouz/multi-client'
    mem_limit: 128m
    hostname: client

  worker:
    image: 'rcsouz/multi-worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT